### PR TITLE
Refactor the RabbitMQ connector

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by ozangunalp — APPROVED** [review]
Ok for me. 
As a future step I'd remove `RabbitMQConsumerHelper` by moving
`declareExchangeIfNeeded` and `getExchangeName` to the `RabbitMQClientHelper`, and the remaining methods to the IncomingRabbitMQChannel.

**Comment by cescoffier** [comment]
@ozangunalp  I can do that right now.

**Comment by cescoffier** [comment]
ah ah.... I just pushed another change.

**Comment by cescoffier** [comment]
let me re-open another PR

**Pull request merged**
