### PR TITLE
Implementation of a new wiring algorithm

### LINKED ISSUE #414: NPE when broadcasting emitted messages to SSE
The following example:

```java
  @Inject
  @Channel("issues")
  Emitter<Status> emitter;

  @Inject
  @Channel("issues-out")
  Publisher<Status> status;

  @Incoming("issues")
  @Outgoing("issues-out")
  @Broadcast
  public Status publish(Status status) {
     return status;
  }

   @GET
   @Path("/issues/status")
   @Produces(MediaType.SERVER_SENT_EVENTS)
   @SseElementType(MediaType.APPLICATION_JSON)
   public Publisher<Status> streamIssues() {
        return status;
    }

   @GET
   @Path("/issues/collect")
   public void collectIssues() {
        fetchIssues().stream()
                     .map(i -> { emitter.send(new Status(i); return i})
                     .forEach(i.persist());
    }
```

Results in:

```
Caused by: java.lang.NullPointerException: Processor must not be null
at java.util.Objects.requireNonNull(Objects.java:228)
at org.eclipse.microprofile.reactive.streams.operators.core.Stages$ProcessorStage.<init>(Stages.java:175)
at org.eclipse.microprofile.reactive.streams.operators.core.PublisherBuilderImpl.via(PublisherBuilderImpl.java:186)
at io.smallrye.reactive.messaging.ProcessorMediator.connectToUpstream(ProcessorMediator.java:31)
at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$null$5(MediatorManager.java:210)
at java.util.Optional.ifPresent(Optional.java:159)
at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$weaving$6(MediatorManager.java:209)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at io.smallrye.reactive.messaging.extension.MediatorManager.weaving(MediatorManager.java:204)
at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:188)
at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
... 14 more
```

### PR DESCRIPTION
**Pull request by cescoffier**
The previous algorithm led to chicken-and-egg issues as the traversal of the graph and the instantiation of the component was made in a single step. 

This new algorithm distinguishes the two phases.
First, the resolution phase looks at the metadata and components (emitter, channels, connectors, and mediators) and assembles the graph. Once built, the graph is validated to detect wiring issues (missing broadcast, missing upstream/downstream...). These issues are reported to the user before starting anything.  

After the validation, the materialization happens. It actually creates the managed objects and connects everything. 

In comparison to the first algorithm, this new one:

* improves error reporting - error messages have been clarified
* supports some topologies not handled before (having a channel, a processor, and an emitter in the same class)
* detect more issues before the application is even started. 

It fixes #414, #879, and https://github.com/quarkusio/quarkus/issues/12820

### CODE REVIEW

**Review by kenfinnigan — COMMENTED** [review]
Should all the exception classes you've added use defined exception message codes as we do for other exceptions?

**Comment by cescoffier** [comment]
@kenfinnigan These exceptions used tailored messages. I don't believe our current approach provides that flexibility (but I may be wrong). It needs iterations on lists, and for some, actually, type checks. Having a class doing to work to create a "naked" exception that just has the error message does not bring much, because anyway, it won't be able to translate it.

**Comment by cescoffier** [comment]
@kenfinnigan I just tried, and yes, it requires a _message_, and I can't pass a message as it's tailored in the exceptions themselves.

**Comment by kenfinnigan** [comment]
No worries, thanks for verifying

**Comment by cescoffier** [comment]
@kenfinnigan Did you review this PR?

**Review by kenfinnigan — APPROVED** [review]
Sorry, forgot to come back to it after the exception questions

**Pull request merged**
