### PR TITLE
Update CI to build the project with Java 8, 11, 16 and 17-EA

### PR DESCRIPTION
**Pull request by cescoffier**
Update GitHub action workflows to build the project using Java 8, 11, 16, and 17-EA.

### CODE REVIEW

**Comment by cescoffier** [comment]
@Ladicek It looks like smallrye fault tolerance fails on java 17.

**Comment by ozangunalp** [comment]
Reading yaml indentations is a joy!
This looks good to me but GH still expects "Build with Java 15".

**Comment by cescoffier** [comment]
> Reading yaml indentations is a joy!

Yes.... I hate yaml. The formatter updated the format and broke yamllint... 

> This looks good to me but GH still expects "Build with Java 15".

This is because the main branch still has this check (until this PR is merged).

@Ladicek may have an idea to re-enable the FT tests. I'm going to test in a few minutes.

**Comment by Ladicek** [comment]
> > This looks good to me but GH still expects "Build with Java 15".
> 
> This is because the main branch still has this check (until this PR is merged).

Actually I think the set of _required_ checks is configured in the settings of the repository. This one could be removed I think.

> @Ladicek may have an idea to re-enable the FT tests. I'm going to test in a few minutes.

Yea I'm updating Weld in SRye FT too: https://github.com/smallrye/smallrye-fault-tolerance/pull/478 That's the only problematic thing. (Actually JBoss Class File Writer, brought in by Weld.)

**Pull request merged**
