### PR TITLE
Handle default exchange when the name is empty string in quotes.

### PR DESCRIPTION
**Pull request by ozangunalp**

### CODE REVIEW

**Comment by hjklapp** [comment]
@ozangunalp yes, making `getExchangename` public is similar to what I thought.

Seems good!

**Comment by ozangunalp** [comment]
Yes we can do that, let me add a word to the documentation as well.

**Comment by hjklapp** [comment]
I cannot fork this repository twice, so here is a draft for the doc changes.

bottom of docs/rabbitmq/sending-messages-to-rabbitmq.md
```md
## Sending to specific queues via the default exchange

To send a message to a specific queue (usually a reply queue), you have to configure the default exchange as an outgoing channel and set the name of the queue as routing key in the message metadata. The name of the exchange needs to be set to `""`.

```properties
mp.messaging.outgoing.channel-name-for-default-exchange.connector=smallrye-rabbitmq
mp.messaging.outgoing.channel-name-for-default-exchange.exchange.name=""
```

line 91 of rabbitmq/RabbitMQConnector.java
```md
@ConnectorAttribute(name = "exchange.name", direction = INCOMING_AND_OUTGOING, description = "The exchange that messages are published to or consumed from. If not set, the channel name is used. If set to \"\", the default exchange is used.", type = "string")
```

**Comment by ozangunalp** [comment]
I've pushed the changes @hjklapp Thank you very much!

**Review by cescoffier — APPROVED** [review]

**Comment by hjklapp** [comment]
@ozangunalp Thank you for taking care of the PR!
Next time we don't have to use the vert.x client directly 🙂

**Comment by felipemendes-maplink** [comment]
Hello Folks! Can anyone tell me which release this feature will be available?

**Comment by felipemendes1994** [comment]
Hello Folks! Can anyone tell me which release this feature will be available?

**Pull request merged**
