### PR TITLE
Update the microprofile reactive messaging  dependency to 3.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
@ozangunalp, for some weird reason, revapi is complaining... we would need to have a look before the release.

**Review by ozangunalp — APPROVED** [review]

**Comment by ozangunalp** [comment]
@cescoffier I pushed a diff to ignore revapi changes.

**Comment by cescoffier** [comment]
@ozangunalp Thanks!  Yes, I don't understand that "breakage". These methods have been added months ago. MAybe the revapi baseline must be updated.

**Comment by ozangunalp** [comment]
Because we have a 4.0.0.RC1 release, next 4.x will be compared to that release. I think ignoring is safer, as with jakarta release we'll have bunch of changes.

**Pull request merged**
