### PR TITLE
Draft - AWS - SQS support

### PR DESCRIPTION
**Pull request by holomekc**
Hi I started with an implementation. There is still a lot of work to do. So help would be welcome. I created the pr, because maybe reviews, questions, help is easier this way.

Progress:
- [ ] SQS
  - [x] Sending messages
  - [x] Sending batch messages
  - [x] Outgoing channel
  - [x] Get queue url from name
  - [x] Create queue if not exists
  - [x] Receive messages
  - [x] Incoming channel
  - [x] Delete / Confirm messages
  - [x] Delete / Confirm batch messages
  - [ ] Testing
    - partially. I started with a WeldTestBase and added some tests for consuming and sending messages. There is still a lot to do. 
  - [ ] More config options
  - [ ] Logging
  - [ ] Error handling
  - [ ] OpenTelemetry (prepared)
  - [ ] Health
  - [ ] Graceful shutdown
    - Partially. For the tests I was forced to add some logic here already. It is not done by far. I just made sure that the consumer is closed properly. It does not wait for the processing of the messages though. Probably more is still open.
- [ ] SNS
  - [ ] TODO

### CODE REVIEW

**Comment by holomekc** [comment]
Some questions.
- client configuration. Although I can describe some of the settings, it is very difficult to cover the complete AWS SDK config. Especially the credentials provider contain so many ways to configure them. I have the feeling I would reimplement the quarkiverse solution for SQS. I am not sure if this is wise. Any ideas?
- delete batching. I am not sure regarding the emitter approach.

**Comment by ozangunalp** [comment]
Thanks for this, I'll give it a spin as soon as possible and make some remarks. 
In the meantime there is now a connector contributor guide if you want to check out : https://smallrye.io/smallrye-reactive-messaging/latest/concepts/contributing-connectors

**Comment by holomekc** [comment]
Hi @ozangunalp ,

Thx for the feedback. Yes I noticed the guide. I read it partially already. I think I covered most things already by accident. Well or by checking some other connector implementations. I will recheck to make sure that I am not missing something.

A huge topic is the configuration of the AWS SDK client. I did not tackle that yet, because I am not sure what the best approach is.

**Comment by holomekc** [comment]
Hi Team,

I stop this contribution. I have no energy to continue it. Sorry for that.

Br,
Chris

**Pull request closed without merging**
