### PR TITLE
Ability to use a supplied SSLContext in the AMQP connector

### PR DESCRIPTION
**Pull request by kabir**
This needs a vertx-amqp-client release containing https://github.com/vert-x3/vertx-amqp-client/pull/80.

Keeping it as a draft PR until that has happened and I can remove the SNAPSHOT version.

### CODE REVIEW

**Comment by kabir** [comment]
@cescoffier @ozangunalp Updated and no longer a draft. CI will fail until we have the vert.x stuff :-)

**Comment by kabir** [comment]
Converting to draft again while waiting for vert.x changes which will need some adjustments on this side

**Comment by kabir** [comment]
@ozangunalp @cescoffier This should be good to go now. Fingers crossed for the CI which passes locally

**Comment by ozangunalp** [comment]
This looks good to me. 
@kabir do you have anything else to do? 
@cescoffier now that we have vert.x 4.3.4 in dependency this is good to go, wdyt ?

**Comment by cescoffier** [comment]
@ozangunalp Yes!

**Comment by kabir** [comment]
@ozangunalp Nothing from me on the SR side

**Review by ozangunalp — APPROVED** [review]

**Pull request merged**
