### PR TITLE
#388 JavaDoc adjustments

### PR DESCRIPTION
**Pull request by gunnarmorling**
For #388.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@cescoffier As we're breaking clients here anyways -- WDYT about changing timestamp to return `Instant`. It avoids the common ambiguities around using long (sec, ms, us...). We use it consequently in Debezium now and only "render" to long ms at the system boundaries, where external contracts expect us to do so.

**Comment by cescoffier** [comment]
@gunnarmorling Yes, I agree Instant would be better!

**Comment by cescoffier** [comment]
@gunnarmorling do you want to do it in this PR?

**Comment by gunnarmorling** [comment]
Ok, I replaced it in the type itself. But the build is failing with

    The POM for org.apache.maven.plugins:maven-jar-plugin:jar:3.2.0 is missing

Any idea? Do I need any special repo? Also I suppose that update needs to be done in other places? What's your guidelines around breaking compat?

**Comment by cescoffier** [comment]
Ok, it seems that Internet from the Github action builder is collapsing.... I have another PR with weird errors too.

**Comment by gunnarmorling** [comment]
@cescoffier, so build looking good now, but something is wrong with the JDK 13 install on CI. Does this need any documentation update? Migration notes or so, pointing out the breaking nature of the change?

**Comment by gunnarmorling** [comment]
Gentle ping, @cescoffier. Anything else I can or should do for this one? Thx!

**Comment by kenfinnigan** [comment]
i've retriggered the build to make sure it was just an erroneous issue.

Will take a look at changes now too

**Comment by cescoffier** [comment]
Amazing, @gunnarmorling pinged me and @kenfinnigan jumps!

**Comment by gunnarmorling** [comment]
LOL, it's great! Thanks guys! Is there any migration notes or similar that
need updating in regards to the timestamp change?

>

**Pull request merged**
