### PR TITLE
Remove MediatorConfiguration.invokerClass which is never set

### PR DESCRIPTION
**Pull request by geoand**
cc @cescoffier

### CODE REVIEW

**Comment by cescoffier** [comment]
@mkouba It's something you did right?

**Comment by geoand** [comment]
I am going to go ahead and close this because I think I understand what it was added - as a forward looking thing

**Comment by mkouba** [comment]
Well, the original idea was to generate `io.smallrye.reactive.messaging.Invoker` classes in quarkus: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java#L141. But I don't remember the details.

**Comment by geoand** [comment]
Yeah, that's what I figured, I'm looking into implementing exactly what you posted

**Pull request closed without merging**
