### PR TITLE
New release process

### PR DESCRIPTION
**Pull request by ozangunalp**

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM - @jponge can you have a quick look?

**Comment by ozangunalp** [comment]
Btw it is normal that the review release is failing, it doesn't have permission to add review to a PR coming from a fork.

**Comment by cescoffier** [comment]
Yes, you need to push the branch to the main repo and not your fork.

**Comment by jponge** [comment]
I've moved the Mutiny workflow to be local-centric with a `justfile`, and only have actions to push tags to Maven Central, and rebuild the website. I was having too many issues in running the whole workflow in CI, especially with JReleaser not getting the correct commit range.

I have had 0 issue on Mutiny Zero / Vert.x bindings with the standard SmallRye release process, so your mileage varies :-)

**Comment by jponge** [comment]
(I was too quick to send)

The standard workflow is fine, but if it doesn't work and you don't want to spend hours debugging GItHub Actions failures, local steps work quite well.

**Pull request merged**
