### PR TITLE
Bump to Mutiny 2.5.2

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
Not sure about these errors, I'll let people here have a look wether Mutiny introduces bugs or not 😉

**Comment by cescoffier** [comment]
@jponge, I will ask @ozangunalp to check, but yes, something changed. I got the same tests fail twice.

**Comment by ozangunalp** [comment]
Still continuing investigation, I can definitely reproduce breaking tests but don't have any leads yet.

**Comment by cescoffier** [comment]
Seems to be related to `transformToUniAndConcatenate`.

**Comment by jponge** [comment]
2.5.3 coming with fixes

**Pull request closed without merging**
