### PR TITLE
Bump OTel instrumentation to 2.5.0

### PR DESCRIPTION
**Pull request by brunobat**
**Breaking changes.** 
For details see: https://github.com/quarkusio/quarkus/pull/41521

### CODE REVIEW

**Comment by brunobat** [comment]
@ozangunalp leaving this draft here because I was having problems with the pulsar image locally and also I get a test error that looks unrelated:
`SqsClientConfigTest.testRegionConfigMissing:22 
Expecting code to raise a throwable.
`

**Comment by brunobat** [comment]
@ozangunalp I have no idea if these errors are relevant for the PR.

**Comment by ozangunalp** [comment]
That was just the documentation module which provides a sample connector with tracing integration. I've pushed a fix.

**Comment by brunobat** [comment]
@ozangunalp do you think this is good to go?

**Comment by ozangunalp** [comment]
Is it ok if we release 4.22.0 without this one and include it in 4.23 ?

**Comment by brunobat** [comment]
It depends when you want to have this merged on Quarkus... I'm not sure either.
When do you think 4.23 can go in?

**Comment by ozangunalp** [comment]
Ideally, we can cut 4.23 just after with only the OTel update.

**Comment by brunobat** [comment]
When do you think that can happen?

**Comment by gsmet** [comment]
Ideally, I think we would need this upgrade merged in Quarkus by next Tuesday.

Which means we need the release to happen very very soon (release time + CI time).

**Comment by ozangunalp** [comment]
Rebased this on top the 4.22.0 release. 

If I am not mistaken this means RM will be incompatible with OTel 1.x. 
I'll release 4.23.0 to include only this PR.

**Review by ozangunalp — APPROVED** [review]

**Comment by brunobat** [comment]
> Rebased this on top the 4.22.0 release.
> 
> If I am not mistaken this means RM will be incompatible with OTel 1.x. I'll release 4.23.0 to include only this PR.

Yes, this is a Breaking Change for the OTel side. IT should be on the release notes.

**Pull request merged**
