### PR TITLE
Upgrade to Mutiny 2.6.0 with JCTools

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
@ozangunalp @cescoffier fear the upgrade, anything can go wrong 🤣

**Comment by ozangunalp** [comment]
@jponge well it is green

**Comment by jponge** [comment]
> @jponge well it is green

I'm scared it passes all 4 tests

**Comment by cescoffier** [comment]
It passes even the flaky tests...

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
@ozangunalp this would need to be in a new minor, as it changes quite some stuff internally.

**Comment by ozangunalp** [comment]
@cescoffier I've assigned it to 4.20.0 so the release after the next

**Comment by jponge** [comment]
Do you have any idea of the timeframe? (to plan the Quarkus update)

**Comment by cescoffier** [comment]
I think the timing is good, I do not see why we should delay it. The only consideration was that we need a way to release previous version to support the Quarkus LTS.

**Review by cescoffier — APPROVED** [review]

**Review by ozangunalp — APPROVED** [review]

**Comment by jponge** [comment]
:part

**Pull request merged**
