### PR TITLE
Fix flaky pause resume test

### LINKED ISSUE #1389: Flaky test -  PauseResumeTest.testRebalanceDuringPausedWithDifferentPartitions:281
I believe it's due to the pause/resume cycle modification that was introduced recently.

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #1389

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Why is it still in draft? Not convinced by the fix?

**Comment by ozangunalp** [comment]
Indeed. And I wasn't able to reproduce the flakiness on my fork in the first place.  I'll need take a look on these tests overall.

**Comment by ozangunalp** [comment]
Ok two greens in a row let's merge this.

**Comment by cescoffier** [comment]
Merged!

**Pull request merged**
