### PR TITLE
#631 Memoize KafkaSink retries config and retry only if above 0

### PR DESCRIPTION
**Pull request by pcasaes**
@cescoffier 
This solves issue #631 

The problem was in the the `config.getRetries()` which is performing an expensive regular expression and it was doing this for every produced message. The solution here is to memo the retry value to a field and only apply the retry code if above 0.

### CODE REVIEW

**Comment by pcasaes** [comment]
Thanks @kenfinnigan . I fixed an error in the commit message.

**Comment by cescoffier** [comment]
Thanks! 

As it seems important enough, I'm going to cut a micro release with this fix.

**Comment by pcasaes** [comment]
I took a look at the config code performing that regular expression
https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/EnvConfigSource.java

I did a quick test replacing the regexp with a simple for loop and string builder. Saw performance gains above 2x. Worth opening a PR for that?

Looking at the code also made me realize that setting the retry property and not relying on the default would mitigate #631

**Comment by cescoffier** [comment]
Yes, go ahead!

**Comment by pcasaes** [comment]
@kenfinnigan maybe you can take a look
https://github.com/smallrye/smallrye-config/pull/341

Noticed you were one of the last to touch that file.

**Pull request merged**
