### PR TITLE
Provide the infrastructure to support health reporting

### PR DESCRIPTION
**Pull request by cescoffier**
Preliminary work to support health support.

What's not covered by this PR:

* the module exposing the reports to MP Metrics
* the update of the existing connectors to support readiness and liveness health checks

The implemented approach avoids having the provider and connectors depending on MP Health directly.

### CODE REVIEW

**Comment by cescoffier** [comment]
When we did that for Metrics it's been a bit of a mess to mitigate the optionality in Quarkus (we had to update some bean class at build time to veto them). That "fix" would not work here. The approach I used avoids this, as we would have a new module exposing the MP Health from these internal types.

**Comment by kenfinnigan** [comment]
And the new module would be in SRye RM or in Quarkus?

**Comment by cescoffier** [comment]
Smallrye, it will be in SmallRye Reactive Messaging.

**Comment by cescoffier** [comment]
let me add this module as part of this PR, so you can see the "whole" picture (minus the connector. part)

**Comment by cescoffier** [comment]
@kenfinnigan I've added the MP Health support

**Pull request merged**
