### PR TITLE
Decorator API for Publisher & Subscribers, Outgoing Message Interceptors

### PR DESCRIPTION
**Pull request by ozangunalp**
There have been previous discussions on message interceptors #1141 

- Using CDI interceptors for Reactive Messaging is not possible as consuming methods callbacks or stream processors are not called through CDI.
- Using CDI decorators was discussed for intercepting calls to Emitters.
- Another use case is to intercept outgoing messages for adapting outgoing payload and intercepting transmission result #1162.
- Interceptors need a way to access some sort of call context: i.e incoming message trace or `@RequestScoped` beans. More recently there is a need to improve OpenTelemetry support by propagating traces through RM streams #1784.

An internal `PublisherDecorator` extension point already exists for incoming channels, which is used for metrics and Vert.x context association.

This PR
- Moves the existing `PublisherDecorator` to the API module
- Adds a `SubscriberDecorator` for decorating `Multi`s that are sources for subscribers in the channel graph.
- Both decorators are prioritized and the graph wiring will call them from highest to lowest priority.
- They receive the channel name and `isConnector` flag for distinguishing channels bound to a connector.
- Introduces a default implementation of `SubscriberDecorator` which discovers `OutgoingInterceptor` beans for attaching interceptors to channels. 
- `OutgoingInterceptor`s can alter outgoing messages with `onMessage` callback, and when supported by the connector (Kafka and MQTT) can access transmission results with`onMessageAck` callback.

### CODE REVIEW

**Comment by Ladicek** [comment]
I didn't review properly, but I'd suggest to avoid extending `Prioritized`. Instead, users should annotate an interceptor with `@Priority`. That's consistent with how CDI interceptors are declared. Also,  invocation order of interceptors should be from lowest priority value to highest priority value, to be consistent with CDI interceptors (see https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0.html#use_of_the_priority_annotation_in_ordering_interceptors).

**Comment by ozangunalp** [comment]
During my tests I couldn't reproduce CDI ordering the instances by default from the `@Inject @Any Instance<A> instances` injection. 
I changed the doc to match the implementation, `PublisherDecorator`s, `SubscriberDecorator`s and `OutgoingInterceptor`s invoked ordered from highest priority to lowest (from the least priority value to the greatest). It is the case for `MessageConverter`s, I added a clarification to the documentation as well. 

I see that `WeldInstance` does come with an instance comparator taking into account both `Prioritized` and `@Priority`. But we can't use it. Therefore for the sake of simplicity I am keeping only the `Prioritized` to describe the bean priority.

**Comment by Ladicek** [comment]
Ah, right, iterating through `Instance` doesn't consider priority. Weld has proprietary means to do so, and ArC does guarantee order, but that's also a proprietary extension. You can use CDI mechanisms directly only when you need a single instance out of multiple. Oh well.

**Review by cescoffier — APPROVED** [review]
LGTM!

**Pull request merged**
