### PR TITLE
Fix Kafka producer concurrency settings

### PR DESCRIPTION
**Pull request by cescoffier**
Do not limit the processor request with the Kafka `max.in.flights.requests.per.connection`, as that setting is per batch or per message. 

This improves a lot (* 100) the throughput of the provider.

### CODE REVIEW

**Comment by cescoffier** [comment]
CC @pcasaes

**Review by kenfinnigan — APPROVED** [review]

**Comment by pcasaes** [comment]
If I understood correctly this completely decouple Kafka's `max.in.flight.requests.per.connection` from the stream producer?

**Comment by pcasaes** [comment]
Wow. just performed a test here. Huge difference!

**Comment by cescoffier** [comment]
@pcasaes Yes, that link was a misconception as the _request_ is actually the number of sent batches, not messages.  The situation is much better now where the `batch.size` and `linger.ms` are controlling when batches are sent. Depending on the size of messages and latency, you can achieve max throughput by configuring the `max-inflight`, `batch.size`, and `linger.ms`.

**Pull request merged**
