### PR TITLE
[RabbitMQ] Add the possibility to configure DLQ DLX and TTL

### PR DESCRIPTION
**Pull request by andr3adc**
Regarding the issue:  https://github.com/smallrye/smallrye-reactive-messaging/issues/2181

Changes:
- dead-letter-ttl attribute added
- dead-letter-dlx attribute added
- dead-letter-dlx-routing-key attribute added

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks, it looks good to me. Let's see what Ozan says.

**Comment by ozangunalp** [comment]
Great addition! I actually had a branch laying around with this. 
@andr3adc Could we mention in the attribute descriptions that this is only used when automatically declare DLQ is enabled ?

**Comment by andr3adc** [comment]
Yes, of course! I'm adding a new commit with the updated descriptions.

**Review by ozangunalp — APPROVED** [review]

**Comment by andr3adc** [comment]
Thank you! Can't wait to see it operative in Quarkus :P

**Pull request merged**
