### PR TITLE
Fix MutinyEmitter so it works with non Message typed messages

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Few things still to sort out, but wanted to get the code up for review.

- I know https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndForgetInjectionTest.java#L102 is failing because the `IllegalArgumentException` is being "swallowed". I'm not sure how to "get it out"
- https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndForgetInjectionTest.java#L102 https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndAwaitInjectionTest.java#L92 and https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndAwaitInjectionTest.java#L103 all fail due to a condition timeout. I'm not sure why yet, if there's an obvious mistake I've made, please shout!

**Comment by cescoffier** [comment]
@kenfinnigan 

The CI is failing:
```
2020-09-22T06:17:14.6649310Z [INFO] Results:
2020-09-22T06:17:14.6649567Z [INFO] 
2020-09-22T06:17:14.6649830Z [ERROR] Failures: 
2020-09-22T06:17:14.6650707Z [ERROR]   MutinyEmitterAndForgetInjectionTest.testWithNull:108 
2020-09-22T06:17:14.6651556Z Expecting:
2020-09-22T06:17:14.6651808Z  <false>
2020-09-22T06:17:14.6652060Z to be equal to:
2020-09-22T06:17:14.6652326Z  <true>
2020-09-22T06:17:14.6652564Z but was not.
2020-09-22T06:17:14.6652823Z [ERROR] Errors: 
2020-09-22T06:17:14.6655447Z [ERROR]   MutinyEmitterAndAwaitInjectionTest.testMyMessageBeanWithPayloadsAndAck:59 » ConditionTimeout
2020-09-22T06:17:14.6658070Z [ERROR]   MutinyEmitterAndAwaitInjectionTest.testWithMessages:96 » ConditionTimeout Cond...
2020-09-22T06:17:14.6660502Z [ERROR]   MutinyEmitterAndAwaitInjectionTest.testWithMessagesLegacy:107 » ConditionTimeout
```

**Comment by cescoffier** [comment]
> Few things still to sort out, but wanted to get the code up for review.
> 
> * I know [https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndForgetInjectionTest.java#L102](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterAndForgetInjectionTest.java?rgh-link-date=2020-09-21T19%3A27%3A36Z#L102) is failing because the `IllegalArgumentException` is being "swallowed". I'm not sure how to "get it out"

You don't. Forget is about forgetting. If the subscriber does not pass a failure callback, the Mutiny dropped exception handler will get it.

**Comment by cescoffier** [comment]
@kenfinnigan 

The code should be:

```java
@Override
    public <M extends Message<? extends T>> void sendAndAwait(M msg) {
        Uni.createFrom().emitter(e -> {
            emit(msg);
            e.complete(null);
        }).await().indefinitely();
    }
```

as you are awaiting indefinitely that the emitter completes. 

Now the question is whether we should have such a method. I was thinking about only having `void emit(M m)`, and not the Uni variant `andForget` and `andAwait`. These methods only make sense when you have payload and no way to be notified of the ack/nack.

**Comment by kenfinnigan** [comment]
@cescoffier should be all good now

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks @kenfinnigan !

**Pull request merged**
