### PR TITLE
Make invoker class creation more flexible

### PR DESCRIPTION
**Pull request by geoand**
cc @cescoffier

### CODE REVIEW

**Comment by geoand** [comment]
@kenfinnigan would it be possible to have a release containing this fix?

Thanks

**Comment by kenfinnigan** [comment]
Sure, unless @cescoffier is waiting for anything else?

**Comment by cescoffier** [comment]
Nope, good to go. @kenfinnigan can you cut the release?

**Comment by kenfinnigan** [comment]
Indeedily do

**Comment by geoand** [comment]
Thanks folks!

**Comment by kenfinnigan** [comment]
1.0.6 is out, should be in Central in half or so

**Comment by geoand** [comment]
Thanks @kenfinnigan !

**Pull request merged**
