### PR TITLE
Ignore the item produced by the "write" method when writing to the dead-queue topic

### LINKED ISSUE #675: ClassCastException when a nacked message is sent to the DLQ
The failure strategy 'dead-letter-queue' seems to be broke.

Here is my configuration : 

Producer code : 

```
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.IntegerSerializer
```

```java
@Outgoing("generated-price")
    public Flowable<Integer> generate() {

        return Flowable.interval(5, TimeUnit.SECONDS)
                .map(tick -> random.nextInt(100));


    }
```

Consumer code : 

```
mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.bootstrap.servers=localhost:9092
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
mp.messaging.incoming.prices.group.id=prices-group-local
mp.messaging.incoming.prices.client.id=prices-client-local
mp.messaging.incoming.prices.enable.auto.commit=false
mp.messaging.incoming.prices.failure-strategy=dead-letter-queue
```

```java
@Incoming( "prices" )
    @Outgoing( "double-prices" )
    @Acknowledgment(Acknowledgment.Strategy.POST_PROCESSING)
    public Uni< Integer > consume( final Integer price) {

        log.info("incoming message {}", price);
    
        if(price< 50) {
            return Uni.createFrom().item(price* 2);
        }
        else {
            return Uni.createFrom().failure(new Exception("Price has to be < 50"));
        }
    }
```

I got the following stacktrace when the price is >= 50 : 

```java
2020-07-21 14:19:07,770 ERROR [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-8) SRMSG18207: Unable to dispatch message to Kafka: java.lang.ClassCastException: io.vertx.kafka.client.producer.RecordMetadata cannot be cast to java.lang.Void
        at io.smallrye.context.SmallRyeThreadContext$ContextualFunction.apply(SmallRyeThreadContext.java:76)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at io.smallrye.mutiny.operators.UniSubscribeToCompletionStage$2.onItem(UniSubscribeToCompletionStage.java:44)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribing$1(AsyncResultUni.java:34)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$send$8(KafkaProducerImpl.java:160)
        at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$null$1(KafkaWriteStreamImpl.java:118)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

The application stops to consume new messages and the lag is increasing.

I notice that when I lauch this command : 
```
kafka-console-consumer -bootstrap-server localhost:9092 --topic dead-letter-topic-prices
```
I see an incoming message so the DLQ is correctly populated. 

I use quarkus 1.6

Java : 
λ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #675
Ignore the item produced by the "write" method.

### CODE REVIEW

**Comment by geniusit** [comment]
Thank you for the fix. Do I have to wait for quarkus 1.7 ?
Actually I have this dependency in my `pom.xml` : 
```xml
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
        </dependency>
```

Is it possible to get your fix by excluding / adding some  depdencies ?
Thx

**Comment by cescoffier** [comment]
You would need to add explicit dependencies to smallrye-reactive-messaging-provider and the Kafka connector.

**Comment by geniusit** [comment]
I can't make it work. 

Here is my stack when I manually add the smallrye-reactive-message-provider and smallrye-reactive-message-kafka dependencies. I can't get rid of it

May be that the best is to release a Quarkus 1.6.2 bugfixes ? Would be great!

```java
2020-07-23 10:18:36,833 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:156)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:296)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:42)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:137)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.arc.Arc.initialize(Arc.java:26)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:35)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy_0(ArcProcessor$generateResources-1120260799.zig:72)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy(ArcProcessor$generateResources-1120260799.zig:36)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:218)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:145)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.smallrye.reactive.messaging.health.HealthReporter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:396)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:333)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:396)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:333)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at io.smallrye.reactive.messaging.extension.HealthCenter_Bean.<init>(HealthCenter_Bean.zig:93)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:101)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:109)
        at io.quarkus.arc.Arc.initialize(Arc.java:20)
        ... 19 more
```

Thank you

**Comment by cescoffier** [comment]
Hum... I should have expected this. You need the master version of
Quarkus to get the health support.
Unfortunately, we won't be able to backport this to Quarkus 1.6.x.

Fortunately, 1.7 is not too far away. It should be out next week. A CR1
release is planned this week.

Le jeu. 23 juil. 2020 à 10:23, Bertrand Deweer <notifications@github.com> a
écrit :

**Comment by geniusit** [comment]
Ok no prob! I can wait a little bit

**Pull request merged**
