### PR TITLE
Make execution holder lazy

### PR DESCRIPTION
**Pull request by cescoffier**
@Azquelt Can you try with this one?

### CODE REVIEW

**Comment by Azquelt** [comment]
Yeah, that works for me. I still need a few vertex classes included so that the classes can be loaded by CDI.

**Comment by cescoffier** [comment]
Yes, but. No more runtime part.

**Comment by Emily-Jiang** [comment]
Thank you @cescoffier @Azquelt ! This is a great news!

**Comment by cescoffier** [comment]
Thanks for the feedback! Let's click on the "green" button.

**Comment by cescoffier** [comment]
@kabir it should not change anything, so more a FYI.

**Pull request merged**
