### PR TITLE
Use throwable.toString on reason and cause if message is null

### PR DESCRIPTION
**Pull request by pcasaes**
@cescoffier 

Getting an unchecked exception when producing to DLQ if the reason or cause messages are null.

```
Caused by: java.lang.NullPointerException
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:52) ~[vertx-core-3.9.4.jar:3.9.4]
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:56) ~[vertx-core-3.9.4.jar:3.9.4]
	at io.vertx.core.buffer.impl.BufferFactoryImpl.buffer(BufferFactoryImpl.java:39) ~[vertx-core-3.9.4.jar:3.9.4]
	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:72) ~[vertx-core-3.9.4.jar:3.9.4]
	at io.vertx.kafka.client.producer.impl.KafkaHeaderImpl.<init>(KafkaHeaderImpl.java:36) ~[vertx-kafka-client-3.9.4.jar:3.9.4]
	at io.vertx.kafka.client.producer.impl.KafkaProducerRecordImpl.addHeader(KafkaProducerRecordImpl.java:139) ~[vertx-kafka-client-3.9.4.jar:3.9.4]
	at io.vertx.mutiny.kafka.client.producer.KafkaProducerRecord.addHeader(KafkaProducerRecord.java:148) ~[smallrye-mutiny-vertx-kafka-client-1.2.2.jar:?]
	at io.smallrye.reactive.messaging.kafka.fault.KafkaDeadLetterQueue.handle(KafkaDeadLetterQueue.java:87) ~[classes/:?]
	at io.smallrye.reactive.messaging.kafka.IncomingKafkaRecord.nack(IncomingKafkaRecord.java:132) ~[classes/:?]
```

### CODE REVIEW

**Comment by cescoffier** [comment]
How did you end up with a `null` reason? `nack` should get a reason.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Just got it... `NullPointerException` don't have messages.

**Comment by cescoffier** [comment]
Thanks!

**Comment by pcasaes** [comment]
It got a reason. But the reason had no message. In this case an npe.

**Comment by pcasaes** [comment]
Actually. In the test case the reason is an illegal argument exception with no message. This causes an npe trying to add the kafka header. 

An npe is an exception that often has no message so it would also fail to write to the dlq.

**Pull request merged**
