### PR TITLE
Add rabbitmq quickstart

### PR DESCRIPTION
**Pull request by cdennison**
Implements #1696

### CODE REVIEW

**Comment by ozangunalp** [comment]
@cdennison Thanks for your PR. I think you need to add `merge=true` to the `to-rabbitmq-string` channel for the Emitter to  channel to work.

**Comment by cdennison** [comment]
> @cdennison Thanks for your PR. I think you need to add `merge=true` to the `to-rabbitmq-string` channel for the Emitter to channel to work.

Yes that was the issue - I don't want to introduce merged streams in the quickstart so I just changed the channel name. My updated PR now has a working emitter example.

As a side note if would nice if there was a more helpful error than the following when merge is required:
`[WARNING]
org.jboss.weld.exceptions.DeploymentException: Wiring error(s) detected in application.`

**Comment by cescoffier** [comment]
The detailled error is in the suppressed exceptions. You need to configure
the logger to display them.

**Comment by cdennison** [comment]
@ozangunalp or @cescoffier are you waiting on me to do anything to merge this PR? Thanks

**Comment by ozangunalp** [comment]
@cdennison the quickstart code seems correct. 
I had an issue with the rabbbitmq image you used: the connections were established but no message transmission was taking place. I think there was an authorization issue.

I changed the container to the default rabbitmq image and added the example project to reactor.

**Comment by ozangunalp** [comment]
I don't have the permission to push to your PR: the code is here https://github.com/smallrye/smallrye-reactive-messaging/commits/cdennison/main. Please feel free to review it and integrate into your PR.

**Comment by cdennison** [comment]
@ozangunalp looks good to me - I merged your branch into mine.

**Pull request closed without merging**
