### PR TITLE
Set metrics name for Vertx based clients on mqtt rabbitmq and amqp

### PR DESCRIPTION
**Pull request by ozangunalp**
So that micrometer metrics will collect metrics for the client.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by ozangunalp** [comment]
@cescoffier I've been struggling to test Vert.x net client metrics using micrometer. Am I not supposed to find connection count etc. in the global registry?

**Comment by cescoffier** [comment]
Not sure about connection count (it's a metric per time window).

Do you have any metrics with the expected prefix?

**Comment by cescoffier** [comment]
You cannot do that - you need to be in Quarkus.

The vert.x micrometer metrics are not reporting the same metrics as (new) quarkus-micrometer. I aligned the reported metrics with the other quarkus-micrometer metrics.

The metrics name using `|` are read and interpreted by quarkus-micrometer only.

**Comment by ozangunalp** [comment]
Yes, I later looked the micrometer extension. LGTM with a ad-hoc test.

**Pull request merged**
