### PR TITLE
Add OpenTelemetry tracing to AMQP Connector

### LINKED ISSUE #562: OpenTelemetry support for Kafka and AMQP
This issue is about adding OpenTelemetry support (Trace / Span) to the Kafka and AMQP connectors both for the inbound and outbound direction. 

This issue should introduce a new type of metadata (`OpenTelemetryMetadata`), which would be created by the inbound Kafka and AMQP connector by reading the headers/annotations from the incoming record/message. 

On the outbound side, if the message produced by the application contains `OpenTelemetryMetadata,` the trace/span should be added to the sent record/message.

It should also be possible to create a new "empty" (initial) `OpenTelemetryMetadata` if the application is the source of the message. It should also be possible to customize the data if needed (like a method receiving the metadata and updating them).

CC @pavolloffay, @kenfinnigan

### PR DESCRIPTION
**Pull request by kenfinnigan**
Resolves #562

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I need to verify this works as expected in Quarkus, but it's very similar to the Kafka approach so should be good

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Hum, that does not seem to work. The propagation tests are failing.

**Comment by kenfinnigan** [comment]
Weirdly one of the four tests fails on JDK 11 with a condition timeout, and two of the four fail on JDK 16 with condition timeout.

But JDK 8 and 15 were fine.

**Comment by kenfinnigan** [comment]
Yay! @cescoffier could you re-review?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Just in time for the release :-D

**Comment by kenfinnigan** [comment]
phew!

**Pull request merged**
