### PR TITLE
Connector contributor guide

### PR DESCRIPTION
**Pull request by ozangunalp**
- Moved `SenderProcessor` to provider module
- Added Maven archetype module for creating connectors

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by ozangunalp** [comment]
I think the CI is still flaky because of the eventloop thread count issue.

**Comment by ozangunalp** [comment]
Test flakiness resolved in #2368

**Comment by cescoffier** [comment]
Can you rebase?

**Comment by ozangunalp** [comment]
Done, sorry I didn't see the conflict

**Pull request merged**
