### PR TITLE
Update the Mosquitto version used in test to 1.6.7

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
What's the "Build" job? Where did it come from?

**Comment by cescoffier** [comment]
Trying these github actions thingy...

**Comment by kenfinnigan** [comment]
Let me know how it goes, considering it for all SRye.

Depends on whether it can handle release type jobs, emails, etc

**Comment by cescoffier** [comment]
Right now, it does not work well. Some failure when we try to connect to the port 32769 (and always this one...)

**Pull request merged**
