### PR TITLE
Support RabbitMQ x-queue-type and x-queue-mode

### PR DESCRIPTION
**Pull request by cdmikechen**
The main purpose of this PR is to support `x-queue-typ` and `x-queue-mode` in rabbitmq. 
I have found that relevant issues have been raised before: https://github.com/smallrye/smallrye-reactive-messaging/issues/1782 and https://github.com/quarkusio/quarkus/issues/25754

@cescoffier Hi~ Sorry to disturb you.
I have added some test cases and tested them locally. Do I need to explain this problem in the email list for discussion?

### CODE REVIEW

**Comment by cescoffier** [comment]
I'm not a RabbitMQ expert, @kdubb can you have a look?

**Comment by kdubb** [comment]
As I've said in the referenced issues, I would like to see this implemented as freeform parameters; there are already too many to add manually and with RMQ plugins It becomes impossible.

I've got my own version of the PR but I ran into an issue with SR Config not supporting freeform maps or properties.

@ozangunalp Said there is some way to handle freeform properties and was going to tackle it but that's where it was left off.

**Comment by cescoffier** [comment]
Reactive messaging does not support freeform attributes. So, except if you define your own format (like some json blurb) or use something like we did in kafka (take into account all the attributes with a prefix) I don't see how to implement it. 

Would the latter be an option?

**Comment by kdubb** [comment]
I think the latter is what @ozangunalp was referring to. An explanation of this technique would help move forward on this.

**Comment by cescoffier** [comment]
it's relatively simple. Instead of using the connector attributes, you retrieve the full MicroProfile Config, iterate over the key, and select the values that match your prefix (`mp.messaging.incoming|outgoing.$channel.queue-args.bla=foo`)

However:

- these attributes won't be documented automatically - so you need to document them
- you won't have the type support

**Comment by cdmikechen** [comment]
@cescoffier @kdubb 
In my opinion, these properties are variables that rabbitmq has explicit configuration instructions and definitions for. Only a small number of these variables are defined in case of big version changes. 
If we can declare them exactly in the configs, it will be easier for users to use and locate them, instead of doing a one-time map in a more generic way (maybe hard to use).

**Comment by ozangunalp** [comment]
Sorry for my late reply. First of all, I think we should take this in, we already do support `x-message-ttl` and `x-single-active-consumer`.

I proposed to have free form config for queue args because IIUC "x-arguments" depend on rabbitmq plugins. 
I can collect a list of remaining common args such as `x-max-length-bytes`, `x-max-length`, `x-overflow`, `x-max-priority`, `x-expires`. 

We may not need to add a near-exhaustive list of x-args, as I understand, broker policies are the recommended way of assigning arguments to queues and exchanges.

**Review by ozangunalp — APPROVED** [review]

**Pull request merged**
